version: "3.7"

services:

  api:
    build: ./api
    volumes:
      - ./api:/api

  db:
    image: mysql:8.0.21
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      TZ: Asia/Tokyo
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    command: '--default-authentication-plugin=mysql_native_password'

  nginx:
    image: nginx:1.19-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8888:8888"
